#!/usr/bin/env node
/**
 * gen-docs — deterministic reference docs FROM SOURCE (no hand-maintained copies).
 *
 * Emits docs/reference/{MCP-TOOLS,CLI,CONFIG}.md:
 *   - MCP-TOOLS: live tools/list from bin/mcp-server.mjs against an in-memory db —
 *     the exact names, descriptions and schemas an agent sees.
 *   - CLI: subcommands + per-command flags parsed from bin/cli.mjs, plus its usage text.
 *   - CONFIG: every MIDMEM_* env knob parsed from src/config.mjs with its context line.
 *
 * `--check` regenerates in memory and exits 1 if any file on disk differs — wired into
 * `npm run verify` so reference docs CANNOT drift from the surfaces (the 2026-08-14
 * "30 tools vs 37" rot class, made structurally impossible).
 */
import { spawn } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CORE = path.join(ROOT, 'packages', 'core');
const OUT = path.join(ROOT, 'docs', 'reference');
const HEADER = '<!-- GENERATED by scripts/gen-docs.mjs — do not edit; run `node scripts/gen-docs.mjs` -->\n\n';

function mcpToolsList() {
  return new Promise((resolve, reject) => {
    const p = spawn('node', [path.join(CORE, 'bin', 'mcp-server.mjs')], {
      env: {
        ...process.env,
        MIDMEM_DB_PATH: ':memory:',
        MIDMEM_AUTO_INGEST: '0',
        MIDMEM_LLM_ENABLED: '0',
        MIDMEM_MAINTENANCE: '0',
      },
      stdio: ['pipe', 'pipe', 'ignore'],
    });
    let buf = '';
    const timer = setTimeout(() => { p.kill(); reject(new Error('mcp-server tools/list timed out')); }, 30000);
    p.stdout.on('data', (d) => {
      buf += d;
      const nl = buf.indexOf('\n');
      if (nl >= 0) {
        clearTimeout(timer);
        p.kill();
        try { resolve(JSON.parse(buf.slice(0, nl)).result.tools); }
        catch (e) { reject(e); }
      }
    });
    p.on('error', reject);
    p.stdin.write(JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'tools/list' }) + '\n');
  });
}

function genMcpDoc(tools) {
  let md = HEADER + `# MCP tool reference (${tools.length} tools)\n\n`;
  md += 'The exact surface `bin/mcp-server.mjs` serves (stdio JSON-RPC). Registration recipes: ' +
        '[INTEGRATION-MODES.md](../INTEGRATION-MODES.md).\n\n';
  for (const t of tools) {
    const props = t.inputSchema?.properties || {};
    const required = new Set(t.inputSchema?.required || []);
    md += `## \`${t.name}\`\n\n${t.description}\n\n`;
    const keys = Object.keys(props);
    if (keys.length) {
      md += '| arg | type | required | notes |\n|---|---|---|---|\n';
      for (const k of keys) {
        const p = props[k];
        const type = p.type || (p.items ? 'array' : 'object');
        md += `| \`${k}\` | ${type}${p.items?.type ? `<${p.items.type}>` : ''} | ${required.has(k) ? 'yes' : ''} | ${(p.description || '').replace(/\|/g, '\\|')} |\n`;
      }
      md += '\n';
    } else {
      md += '_No arguments._\n\n';
    }
  }
  return md;
}

function genCliDoc() {
  const src = fs.readFileSync(path.join(CORE, 'bin', 'cli.mjs'), 'utf8');
  const cases = [...src.matchAll(/^\s*case '([a-z-]+)':(.*)$/gm)]
    .map((m) => ({ cmd: m[1], line: m[2] }));
  let md = HEADER + `# CLI reference (${cases.length} commands)\n\n`;
  md += 'Parsed from `packages/core/bin/cli.mjs` (the wrapper `midmem <command>` in a deployment). ' +
        'Flags listed are the ones each command reads; positional args are shown in the usage text below.\n\n';
  md += '| command | flags read |\n|---|---|\n';
  for (const c of cases) {
    const flags = [...new Set([...c.line.matchAll(/flags\.([a-zA-Z]+)/g)].map((m) => `--${m[1]}`))];
    md += `| \`${c.cmd}\` | ${flags.map((f) => `\`${f}\``).join(' ') || '—'} |\n`;
  }
  // The MAIN usage string is the `Usage: ocmw …` one; sub-usages (`prospective`, `vectors`) are the
  // default branches of their own sub-switches and must not shadow it (they did until 2026-09-24).
  const usage = src.match(/out\('(Usage: ocmw[\s\S]*?)'\);/);
  if (usage) md += '\n## Usage text (verbatim from the CLI)\n\n```\n' + usage[1].replace(/\\n/g, '\n') + '\n```\n';
  const subs = [...src.matchAll(/out\('(Usage: (?!ocmw)[\s\S]*?)'\);/g)].map((m) => m[1].replace(/\\n/g, '\n'));
  if (subs.length) md += '\n## Sub-command usage\n\n```\n' + subs.join('\n\n') + '\n```\n';
  return md;
}

function genConfigDoc() {
  const src = fs.readFileSync(path.join(CORE, 'src', 'config.mjs'), 'utf8');
  const lines = src.split('\n');
  let md = HEADER + '# Configuration reference (env knobs)\n\n';
  md += 'Every knob honors the `MIDMEM_` prefix (legacy `OCMW_` still read as fallback). ' +
        'Parsed from `packages/core/src/config.mjs`; the context column is the source line, so the ' +
        'default is visible verbatim. Canonical deployment pattern: keep all values in ONE shared ' +
        'env file sourced by every wrapper (see INTEGRATION-MODES §5).\n\n';
  md += '| env var | source context (default visible) |\n|---|---|\n';
  const seen = new Set();
  for (const line of lines) {
    for (const m of line.matchAll(/env\('([A-Z_0-9]+)'\)/g)) {
      const name = `MIDMEM_${m[1]}`;
      if (seen.has(name)) continue;
      seen.add(name);
      md += `| \`${name}\` | \`${line.trim().replace(/\|/g, '\\|').slice(0, 140)}\` |\n`;
    }
  }
  md += `\n_${seen.size} env knobs._\n`;
  return md;
}

async function main() {
  const check = process.argv.includes('--check');
  const files = {
    'MCP-TOOLS.md': genMcpDoc(await mcpToolsList()),
    'CLI.md': genCliDoc(),
    'CONFIG.md': genConfigDoc(),
  };
  fs.mkdirSync(OUT, { recursive: true });
  let drifted = [];
  for (const [name, content] of Object.entries(files)) {
    const p = path.join(OUT, name);
    const existing = fs.existsSync(p) ? fs.readFileSync(p, 'utf8') : null;
    if (check) {
      if (existing !== content) drifted.push(name);
    } else if (existing !== content) {
      fs.writeFileSync(p, content);
      console.log(`wrote docs/reference/${name}`);
    } else {
      console.log(`unchanged docs/reference/${name}`);
    }
  }
  if (check) {
    if (drifted.length) {
      console.error(`DOCS DRIFT: ${drifted.join(', ')} out of date — run \`node scripts/gen-docs.mjs\``);
      process.exit(1);
    }
    console.log('docs reference in sync with source');
  }
}

main().catch((e) => { console.error('gen-docs failed:', e.message); process.exit(1); });
